### ISSUE TITLE
Scraping only a certain number of reviews

### ISSUE THREAD

**Issue by Ema8899** [wu258/tripadvisor_scraper#1]
Hello @wu258!

I have a question regarding your code: if I want to get 50 reviews, for example, instead of all of them. Which part would I need to modify?

Thanks!

**Comment by wu258** [comment]
Hi,
is that mean you want to collect 50 reviews from each location? is yes, I have updated my code. hopefully, it will help you.
regards

**Comment by wu258** [comment]
you can change the targe_number=your_number at line 12

**Comment by Ema8899** [comment]
Thanks a lot for your prompt reply! @wu258 

Perfect. Yes, that's what I meant.
